Layout/ExtraSpacing:
    AllowForAlignment: true

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Exclude:
    - tcelfer.gemspec

AllCops:
    TargetRubyVersion: 2.6
    Exclude:
    - exe/tcelfer_test.rb

