Layout/ExtraSpacing:
  AllowForAlignment: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - tcelfer.gemspec

AllCops:
  Exclude:
      - 'tmp/*'
      - 'vendor/**/*'
      - 'vendor/**/.*'
  TargetRubyVersion: 2.6
