require: rubocop-rake

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - tcelfer.gemspec

AllCops:
  Exclude:
      - 'tmp/*'
      - 'vendor/**/*'
      - 'vendor/**/.*'
  TargetRubyVersion: 2.7
  NewCops: enable
